# https://leetcode.com/problems/find-the-difference/
#
# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

def find_the_difference(s, t)
    diff = Hash.new(0)
    s.chars.each { |letter| diff[letter] += 1 }
    t.chars.each { |letter| diff[letter] -= 1 }
    diff.key(-1)
end
